name: Update Stock Data

on:
  schedule:
    - cron: "0 15 * * *"   # 한국 자정 (UTC 15:00)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # ✅ pull/rebase 위해 전체 히스토리 필요

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_html.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main
          git add index.html
          git commit -m "Update stock data" || echo "No changes"
          git push origin main
